name: fecra
description: "FECRA: Foreign exchange currency rate app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  rxdart: ^0.27.7
  collection: ^1.18.0
  mockito: ^5.4.3
  flutter_localizations:
    sdk: flutter
  intl: any
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  gap: ^3.0.1
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  go_router: ^12.1.0
  sqlite3_flutter_libs: ^0.5.18
  drift: ^2.14.1
  path_provider: ^2.1.1
  path: ^1.8.3
  chart_sparkline: ^1.0.14
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.13.2
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  flutter_gen_runner: ^5.3.2
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
